### ISSUE TITLE
Use feature and scenario over describe and it for system tests

### ISSUE THREAD

**Issue by IlkhamGaysin** [dbl-works/rubocop-dbl#21]
Do we follow agile and scrum? if we do probably it's better to have right naming for rspec dsl for system tests

![image](https://user-images.githubusercontent.com/17009998/103636762-7ea08780-4f5b-11eb-8527-c0c0d1a22eb8.png)

**Comment by swiknaba** [comment]
`feature` and `scenario` are capybara specific aliases for `describe` and `it` right? I would in general prefer to keep the RSpec native syntax instead of Capybara specific one, simply because I am more used to RSpec syntax.
No strong opinion here though.

**Comment by IlkhamGaysin** [comment]
@swiknaba yeah, they're Capybara's.
