### ISSUE TITLE
Use norma_case for naming vars

### ISSUE THREAD

**Issue by IlkhamGaysin** [dbl-works/rubocop-dbl#22]
![image](https://user-images.githubusercontent.com/17009998/103774005-f5fa1800-503c-11eb-9634-6fd31dba7609.png)

**Comment by swiknaba** [comment]
I personally find `some_thing_1` more readable than `some_thing1`. Shall we vote?
🐍  = snake_case, e.g. `some_thing_1`
🐫  = normalcase, e.g. `some_thing1`

**Comment by swiknaba** [comment]
@IlkhamGaysin is this closed by https://github.com/dbl-works/rubocop-dbl/pull/26 ?
